# Model Experiments

This notebook is used to experiment with and optimize the selected models:

- Random Forest
- Ridge Regression
- TensorFlow Dense Neural Network

Each model will be trained and improved independently, with a focus on generalization and validation performance. Models will be compared against previous configurations throughout the experimentation process.

The final comparison will be performed once further improvements become marginal relative to the effort required.

In [26]:
from keras import Sequential, Input
from keras.src.callbacks import EarlyStopping
from keras.src.layers import Dense, Dropout
from keras.src.optimizers import Adam
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge
from tensorflow.python.keras.regularizers import l2

from src.common.constants import FINAL_SELECTED_FEATURES
from src.common.schemas import DeepLearningFitParamSchema
from src.modeling.data_utils import load_modeling_data, split_modeling_data, train_and_evaluate_model, preprocess_data

In [27]:
df = load_modeling_data()

train_df, val_df, test_df = split_modeling_data(df)

## Experiment 1 — Random Forest

Train and optimize the Random Forest model as a strong baseline.

Focus on:
- Hyperparameter tuning
- Validation performance
- Generalization
- Avoiding overfitting

Iterate on the configuration until further improvements become marginal.

In [28]:
rf_base_model = RandomForestRegressor(
    n_estimators=400,
    max_depth=20,
    min_samples_split=2,
    min_samples_leaf=2,
    max_features=1.0,
    max_samples=1.0,
    random_state=42,
    n_jobs=-1,
)

rf_base_model, (rf_base_rmse, rf_base_mae, rf_base_r2) = train_and_evaluate_model(train_df, val_df,
                         label="Random Forest Base Model", toggle_evaluate_print=True, disable_plot=True,
                         baseline=FINAL_SELECTED_FEATURES, model=rf_base_model)

target_aqi_day1
  RMSE: 16.0476
  MAE:  10.3983
  R²:   0.8372

target_aqi_day2
  RMSE: 28.2155
  MAE:  19.3990
  R²:   0.5048

target_aqi_day3
  RMSE: 31.3263
  MAE:  22.5330
  R²:   0.4227

target_aqi_day4
  RMSE: 31.7258
  MAE:  23.5333
  R²:   0.4320

**Observation:** Random Forest performs reasonably well for the 1-day-ahead target (`R² = 0.8372`, `RMSE = 16.0476`, `MAE = 10.3983`) but performance drops substantially for Days 2–4, with `R²` falling to `0.42–0.50` and errors increasing. This suggests the current configuration captures short-term AQI patterns better than longer-horizon patterns, so further Random Forest hyperparameter tuning is required.

In [29]:
rf_base_model_r = RandomForestRegressor(
    n_estimators=600,
    max_depth=12,
    min_samples_split=5,
    min_samples_leaf=3,
    max_features=0.8,
    max_samples=0.9,
    random_state=42,
    n_jobs=-1,
)

rf_base_model_r, (rf_base_rmse_r, rf_base_mae_r, rf_base_r2_r) = train_and_evaluate_model(train_df, val_df,
                         label="Random Forest Base Model Regularized", disable_plot=True,
                         baseline=FINAL_SELECTED_FEATURES, model=rf_base_model_r,
                         compare_model=("Random Forest Base Model", (rf_base_rmse, rf_base_mae, rf_base_r2)))

,Target,Random Forest Base Model RMSE,Random Forest Base Model MAE,Random Forest Base Model R²,Random Forest Base Model Regularized RMSE,Random Forest Base Model Regularized MAE,Random Forest Base Model Regularized R²
0,target_aqi_day1,16.047587,10.398290,0.837215,15.816504,10.285093,0.841869
1,target_aqi_day2,28.215522,19.399020,0.504783,27.641673,19.082047,0.524722
2,target_aqi_day3,31.326312,22.533011,0.422727,31.105018,22.321087,0.430854
3,target_aqi_day4,31.725815,23.533278,0.431963,31.866488,23.707509,0.426915
4,Mean,26.828809,18.965900,0.549172,26.607421,18.848934,0.556090

**Observation:** Regularization improved the Random Forest slightly, increasing mean R² from `0.5492` to `0.5561` and reducing mean RMSE from `26.8288` to `26.6074`. The improvement is consistent for Days 1–3 but negligible for Day 4, indicating that the regularization approach is beneficial but the current parameter changes have only a limited impact. Stronger regularization will therefore be tested next.

In [30]:
rf_base_model_r_2 = RandomForestRegressor(
    n_estimators=600,
    max_depth=20,
    min_samples_split=7,
    min_samples_leaf=7,
    max_features=0.85,
    max_samples=0.9,
    random_state=42,
    n_jobs=-1,
)

rf_base_model_r_2, (rf_base_rmse_r_2, rf_base_mae_r_2, rf_base_r2_r_2) = train_and_evaluate_model(train_df, val_df,
                         label="Random Forest Base Model Regularized v2", disable_plot=True,
                         baseline=FINAL_SELECTED_FEATURES, model=rf_base_model_r_2,
                         compare_model=("Random Forest Base Model Regularized", (rf_base_rmse_r, rf_base_mae_r, rf_base_r2_r)))

,Target,Random Forest Base Model Regularized RMSE,Random Forest Base Model Regularized MAE,Random Forest Base Model Regularized R²,Random Forest Base Model Regularized v2 RMSE,Random Forest Base Model Regularized v2 MAE,Random Forest Base Model Regularized v2 R²
0,target_aqi_day1,15.816504,10.285093,0.841869,15.767436,10.236939,0.842849
1,target_aqi_day2,27.641673,19.082047,0.524722,27.292848,18.974586,0.536642
2,target_aqi_day3,31.105018,22.321087,0.430854,30.923929,22.263238,0.437462
3,target_aqi_day4,31.866488,23.707509,0.426915,31.818725,23.738206,0.428632
4,Mean,26.607421,18.848934,0.556090,26.450734,18.803242,0.561396

**Observation:** The second regularization experiment produced only a small improvement over the previous configuration, with mean RMSE decreasing from `26.6074` to `26.4507`, MAE from `18.8489` to `18.8032`, and R² increasing from `0.5561` to `0.5614`. Although the changes to `min_samples_split`, `min_samples_leaf`, `max_features`, and `max_samples` improved the overall result, their individual impact remains limited. The current configuration will be used as the benchmark for the final `n_estimators` experiment.

In [31]:
rf_base_model_r_3 = RandomForestRegressor(
    n_estimators=800,
    max_depth=20,
    min_samples_split=7,
    min_samples_leaf=7,
    max_features=0.85,
    max_samples=0.9,
    random_state=42,
    n_jobs=-1,
)

rf_base_model_r_3, (rf_base_rmse_r_3, rf_base_mae_r_3, rf_base_r2_r_3) = train_and_evaluate_model(train_df, val_df,
                         label="Random Forest Base Model Regularized v3", disable_plot=True,
                         baseline=FINAL_SELECTED_FEATURES, model=rf_base_model_r_3,
                         compare_model=("Random Forest Base Model Regularized v2", (
                                        rf_base_rmse_r_2, rf_base_mae_r_2, rf_base_r2_r_2
                         )))

,Target,Random Forest Base Model Regularized v2 RMSE,Random Forest Base Model Regularized v2 MAE,Random Forest Base Model Regularized v2 R²,Random Forest Base Model Regularized v3 RMSE,Random Forest Base Model Regularized v3 MAE,Random Forest Base Model Regularized v3 R²
0,target_aqi_day1,15.767436,10.236939,0.842849,15.773150,10.232304,0.842735
1,target_aqi_day2,27.292848,18.974586,0.536642,27.296457,19.018086,0.536519
2,target_aqi_day3,30.923929,22.263238,0.437462,30.918054,22.297219,0.437675
3,target_aqi_day4,31.818725,23.738206,0.428632,31.794940,23.745205,0.429486
4,Mean,26.450734,18.803242,0.561396,26.445650,18.823203,0.561604

**Observation:** Increasing `n_estimators` from `600` to `800` produced negligible changes in performance, with mean RMSE improving from `26.4507` to `26.4457` and mean R² from `0.5614` to `0.5616`, while mean MAE slightly worsened. This indicates that increasing the number of trees has reached diminishing returns, so further Random Forest tuning is not justified.

## Experiment 2 — Ridge Regression

Train and optimize the Ridge Regression model as a linear baseline.

Focus on:
- Preprocessing and scaling
- Regularization strength
- Validation performance
- Generalization
- Avoiding overfitting

Iterate on the configuration until further improvements become marginal.

In [32]:
train_df, val_df, test_df = preprocess_data(train_df, val_df, test_df)

In [33]:
ridge_base_model = Ridge(
    alpha=10.0,
    fit_intercept=True,
    solver="auto",
    tol=1e-4,
    max_iter=5000,
)

ridge_base_model, (ridge_base_rmse, ridge_base_mae, ridge_base_r2) = train_and_evaluate_model(train_df, val_df,
                         label="Ridge Regression Base Model", disable_plot=True,
                         baseline=FINAL_SELECTED_FEATURES, model=ridge_base_model,
                         compare_model=("Random Forest Base Model Regularized v3", (
                                        rf_base_rmse_r_3, rf_base_mae_r_3, rf_base_r2_r_3
                         )))

,Target,Random Forest Base Model Regularized v3 RMSE,Random Forest Base Model Regularized v3 MAE,Random Forest Base Model Regularized v3 R²,Ridge Regression Base Model RMSE,Ridge Regression Base Model MAE,Ridge Regression Base Model R²
0,target_aqi_day1,15.773150,10.232304,0.842735,14.398813,10.631519,0.868947
1,target_aqi_day2,27.296457,19.018086,0.536519,26.640181,18.573379,0.558538
2,target_aqi_day3,30.918054,22.297219,0.437675,30.287032,21.520296,0.460395
3,target_aqi_day4,31.794940,23.745205,0.429486,31.786017,23.061679,0.429806
4,Mean,26.445650,18.823203,0.561604,25.778011,18.446718,0.579421

**Observation:** Ridge Regression outperformed the final Random Forest configuration across the mean metrics, improving RMSE from `26.4457` to `25.7780`, MAE from `18.8232` to `18.4467`, and R² from `0.5616` to `0.5794`. The largest improvement was observed for the 1-day-ahead target, while Day 4 remained nearly unchanged. Further Ridge optimization will focus on regularization strength (`alpha`).

In [34]:
ridge_base_model_r = Ridge(
    alpha=0.01,
    fit_intercept=True,
    solver="auto",
    tol=1e-4,
    max_iter=5000,
)

ridge_base_model_r, (ridge_base_rmse_r, ridge_base_mae_r, ridge_base_r2_r) = train_and_evaluate_model(train_df, val_df,
                         label="Ridge Regression Base Model Regularized", disable_plot=True,
                         baseline=FINAL_SELECTED_FEATURES, model=ridge_base_model_r,
                         compare_model=("Ridge Regression Base Model", (
                                        ridge_base_rmse, ridge_base_mae, ridge_base_r2
                         )))

,Target,Ridge Regression Base Model RMSE,Ridge Regression Base Model MAE,Ridge Regression Base Model R²,Ridge Regression Base Model Regularized RMSE,Ridge Regression Base Model Regularized MAE,Ridge Regression Base Model Regularized R²
0,target_aqi_day1,14.398813,10.631519,0.868947,14.265966,10.489315,0.871354
1,target_aqi_day2,26.640181,18.573379,0.558538,26.840461,18.772470,0.551875
2,target_aqi_day3,30.287032,21.520296,0.460395,30.109489,21.517893,0.466703
3,target_aqi_day4,31.786017,23.061679,0.429806,31.580063,22.956517,0.437171
4,Mean,25.778011,18.446718,0.579421,25.698995,18.434049,0.581776

**Observation:** Reducing Ridge's `alpha` to `0.01` produced only a marginal improvement in mean performance, increasing R² from `0.5794` to `0.5818` and reducing RMSE from `25.7780` to `25.6990`. The improvement is too small to justify further `alpha` tuning. The next experiment will test `max_iter` once to verify whether additional iterations affect convergence or performance.

In [35]:
ridge_base_model_r_2 = Ridge(
    alpha=0.01,
    fit_intercept=True,
    solver="auto",
    tol=1e-4,
    max_iter=10000,
)

ridge_base_model_r_2, (ridge_base_rmse_r_2, ridge_base_mae_r_2, ridge_base_r2_r_2) = train_and_evaluate_model(train_df, val_df,
                         label="Ridge Regression Base Model Regularized v2", disable_plot=True,
                         baseline=FINAL_SELECTED_FEATURES, model=ridge_base_model_r_2,
                         compare_model=("Ridge Regression Base Model Regularized", (
                                        ridge_base_rmse_r, ridge_base_mae_r, ridge_base_r2_r
                         )))

,Target,Ridge Regression Base Model Regularized RMSE,Ridge Regression Base Model Regularized MAE,Ridge Regression Base Model Regularized R²,Ridge Regression Base Model Regularized v2 RMSE,Ridge Regression Base Model Regularized v2 MAE,Ridge Regression Base Model Regularized v2 R²
0,target_aqi_day1,14.265966,10.489315,0.871354,14.265966,10.489315,0.871354
1,target_aqi_day2,26.840461,18.772470,0.551875,26.840461,18.772470,0.551875
2,target_aqi_day3,30.109489,21.517893,0.466703,30.109489,21.517893,0.466703
3,target_aqi_day4,31.580063,22.956517,0.437171,31.580063,22.956517,0.437171
4,Mean,25.698995,18.434049,0.581776,25.698995,18.434049,0.581776

**Observation:** Increasing Ridge's `max_iter` produced no change in performance, confirming that the model is already converging before reaching the iteration limit. Further Ridge optimization is therefore unlikely to provide meaningful gains through these hyperparameters.

## Experiment 3 — Dense Neural Network (MLP)

Train and optimize the MLP model as the deep learning model.

Focus on:
- Architecture and capacity
- Regularization
- Learning rate and training configuration
- Validation performance
- Generalization
- Avoiding overfitting

Iterate on the configuration until further improvements become marginal.

In [36]:
mlp_base_model = Sequential([
    Input(shape=(23,)),
    Dense(
        8,
        activation="relu",
        kernel_regularizer=l2(1e-4),
    ),
    Dropout(0.15),
    Dense(4, activation="linear"),
])

mlp_base_model.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss="mse",
)

early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=15,
    restore_best_weights=True,
)

mlp_base_model_fit_params: DeepLearningFitParamSchema = {
    "epochs": 500,
    "batch_size": 32,
    "callbacks": [early_stopping],
    "verbose": 1
}

mlp_base_model, (mlp_base_rmse, mlp_base_mae, mlp_base_r2) = train_and_evaluate_model(train_df, val_df,
                         label="MLP Base Model", disable_plot=True,
                         baseline=FINAL_SELECTED_FEATURES, model=mlp_base_model,
                         compare_model=("Ridge Regression Base Model Regularized", (
                                        ridge_base_rmse_r, ridge_base_mae_r, ridge_base_r2_r
                         )),
                         deep_learning=mlp_base_model_fit_params)

Epoch 1/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 25976.8770 - val_loss: 25855.6230
Epoch 2/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25886.0137 - val_loss: 25790.6250
Epoch 3/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25809.0625 - val_loss: 25722.8027
Epoch 4/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25720.5391 - val_loss: 25644.6758
Epoch 5/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25620.4160 - val_loss: 25550.8379
Epoch 6/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25515.8535 - val_loss: 25440.0293
Epoch 7/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25373.8555 - val_loss: 25306.7031
Epoch 8/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25219.6758 - val_loss: 25149.5215
Epoch 9/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25035.5938 - val_loss: 24962.2656
Epoch 10/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24764.0566 - val_loss: 24741.5938
Epoch 11/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24482.7266 - val_loss: 24486.3809
Epoch 12/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24174.8477 - val_loss: 24209.9668
Epoch 13/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23796.7305 - val_loss: 23899.4473
Epoch 14/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 23375.8496 - val_loss: 23559.6582
Epoch 15/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22976.1699 - val_loss: 23202.1172
Epoch 16/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22510.3926 - val_loss: 22818.2461
Epoch 17/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22026.9746 - val_loss: 22431.1348
Epoch 18/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21607.8789 - val_loss: 22019.1016
Epoch 19/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21132.2090 - val_loss: 21602.0684
Epoch 20/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20566.7734 - val_loss: 21156.5078
Epoch 21/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20030.3809 - val_loss: 20699.5996
Epoch 22/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19524.4316 - val_loss: 20196.0234
Epoch 23/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18854.4297 - val_loss: 19671.7422
Epoch 24/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18257.9609 - val_loss: 19111.4180
Epoch 25/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17661.2734 - val_loss: 18526.7539
Epoch 26/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17108.1465 - val_loss: 17946.9863
Epoch 27/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16246.7812 - val_loss: 17354.0859
Epoch 28/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15755.5654 - val_loss: 16767.0684
Epoch 29/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 14931.6875 - val_loss: 16170.5801
Epoch 30/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 14430.1914 - val_loss: 15571.2666
Epoch 31/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13533.3750 - val_loss: 14986.2070
Epoch 32/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13118.5957 - val_loss: 14399.0039
Epoch 33/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12527.3877 - val_loss: 13837.3438
Epoch 34/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12017.6621 - val_loss: 13291.6631
Epoch 35/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11353.0977 - val_loss: 12770.7988
Epoch 36/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10840.9268 - val_loss: 12269.2061
Epoch 37/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10574.4355 - val_loss: 11790.9443
Epoch 38/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10036.8398 - val_loss: 11328.9258
Epoch 39/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9782.5264 - val_loss: 10879.9258
Epoch 40/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9352.9951 - val_loss: 10457.6875
Epoch 41/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8898.5615 - val_loss: 10049.5547
Epoch 42/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8637.4717 - val_loss: 9656.3779
Epoch 43/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8463.4629 - val_loss: 9279.1992
Epoch 44/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8259.3447 - val_loss: 8948.3682
Epoch 45/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7960.9917 - val_loss: 8636.9092
Epoch 46/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7624.5205 - val_loss: 8340.1191
Epoch 47/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7469.1909 - val_loss: 8090.0527
Epoch 48/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7433.0425 - val_loss: 7853.6377
Epoch 49/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7232.0894 - val_loss: 7622.6494
Epoch 50/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7169.5200 - val_loss: 7434.1436
Epoch 51/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7219.0649 - val_loss: 7243.9033
Epoch 52/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6999.2524 - val_loss: 7091.2642
Epoch 53/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6933.5103 - val_loss: 6982.9673
Epoch 54/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6777.5508 - val_loss: 6861.2949
Epoch 55/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6830.2456 - val_loss: 6724.3848
Epoch 56/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6737.3135 - val_loss: 6632.4531
Epoch 57/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6627.5601 - val_loss: 6530.1699
Epoch 58/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6728.1138 - val_loss: 6447.2734
Epoch 59/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6664.4331 - val_loss: 6359.0308
Epoch 60/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6336.9736 - val_loss: 6273.9692
Epoch 61/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6351.1519 - val_loss: 6207.2012
Epoch 62/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6624.9639 - val_loss: 6182.3135
Epoch 63/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6363.8208 - val_loss: 6125.8687
Epoch 64/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6242.1953 - val_loss: 6042.6260
Epoch 65/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6302.1934 - val_loss: 6000.1958
Epoch 66/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6407.5356 - val_loss: 5996.3379
Epoch 67/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6161.3203 - val_loss: 5955.6733
Epoch 68/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6082.4302 - val_loss: 5910.8364
Epoch 69/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6320.4014 - val_loss: 5877.3779
Epoch 70/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6121.3413 - val_loss: 5816.9961
Epoch 71/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6250.2300 - val_loss: 5793.2681
Epoch 72/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5940.0923 - val_loss: 5748.1606
Epoch 73/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5977.7329 - val_loss: 5705.0874
Epoch 74/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6144.8179 - val_loss: 5677.9326
Epoch 75/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5848.0347 - val_loss: 5655.6743
Epoch 76/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5930.0693 - val_loss: 5615.3872
Epoch 77/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6055.8433 - val_loss: 5577.7476
Epoch 78/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5779.5161 - val_loss: 5568.0400
Epoch 79/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5791.4648 - val_loss: 5521.0977
Epoch 80/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5825.7310 - val_loss: 5484.0405
Epoch 81/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5637.0571 - val_loss: 5431.1626
Epoch 82/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5865.1260 - val_loss: 5393.2471
Epoch 83/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5458.6587 - val_loss: 5359.1870
Epoch 84/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5543.2051 - val_loss: 5314.6680
Epoch 85/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5668.0923 - val_loss: 5280.1436
Epoch 86/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5806.1606 - val_loss: 5244.8989
Epoch 87/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5689.1611 - val_loss: 5224.7930
Epoch 88/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5731.1709 - val_loss: 5182.5635
Epoch 89/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5504.5571 - val_loss: 5152.2656
Epoch 90/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5318.7808 - val_loss: 5139.8955
Epoch 91/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5441.0093 - val_loss: 5125.0181
Epoch 92/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5386.7188 - val_loss: 5078.3018
Epoch 93/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5300.0630 - val_loss: 5029.1138
Epoch 94/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5442.3110 - val_loss: 4992.4385
Epoch 95/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5395.6982 - val_loss: 4961.5269
Epoch 96/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5318.5425 - val_loss: 4915.8911
Epoch 97/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5206.4502 - val_loss: 4868.3911
Epoch 98/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5145.1562 - val_loss: 4821.4438
Epoch 99/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5100.5273 - val_loss: 4795.7734
Epoch 100/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5103.8818 - val_loss: 4760.0117
Epoch 101/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5257.0005 - val_loss: 4726.6738
Epoch 102/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4948.4062 - val_loss: 4683.1099
Epoch 103/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5114.4595 - val_loss: 4644.9141
Epoch 104/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4999.6904 - val_loss: 4614.1909
Epoch 105/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4983.5625 - val_loss: 4596.2109
Epoch 106/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4810.6958 - val_loss: 4549.6138
Epoch 107/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4876.6050 - val_loss: 4486.4033
Epoch 108/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4934.8276 - val_loss: 4448.9478
Epoch 109/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4772.9453 - val_loss: 4407.4443
Epoch 110/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4837.4224 - val_loss: 4359.1245
Epoch 111/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4820.3706 - val_loss: 4316.3545
Epoch 112/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4572.0913 - val_loss: 4262.5571
Epoch 113/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4750.1768 - val_loss: 4215.8579
Epoch 114/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4624.4248 - val_loss: 4159.9956
Epoch 115/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4556.4683 - val_loss: 4104.4087
Epoch 116/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4788.4473 - val_loss: 4098.5869
Epoch 117/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4537.8701 - val_loss: 4061.0530
Epoch 118/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4429.5967 - val_loss: 4034.4954
Epoch 119/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4612.3530 - val_loss: 4005.2671
Epoch 120/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4557.0269 - val_loss: 3973.3867
Epoch 121/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4539.3882 - val_loss: 3921.9631
Epoch 122/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4265.0488 - val_loss: 3876.2473
Epoch 123/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4128.3330 - val_loss: 3826.2139
Epoch 124/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4244.6772 - val_loss: 3764.5183
Epoch 125/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4061.9263 - val_loss: 3703.6626
Epoch 126/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3964.0735 - val_loss: 3645.5447
Epoch 127/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4259.5693 - val_loss: 3610.9128
Epoch 128/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4134.1621 - val_loss: 3592.2427
Epoch 129/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4036.6770 - val_loss: 3544.1345
Epoch 130/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4094.4404 - val_loss: 3477.7695
Epoch 131/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3957.7729 - val_loss: 3443.1599
Epoch 132/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3789.0891 - val_loss: 3391.5601
Epoch 133/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4038.0007 - val_loss: 3349.0295
Epoch 134/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3958.2625 - val_loss: 3312.2058
Epoch 135/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3733.2485 - val_loss: 3265.5186
Epoch 136/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3813.2739 - val_loss: 3212.6360
Epoch 137/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3629.9443 - val_loss: 3175.3054
Epoch 138/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3744.4036 - val_loss: 3131.6909
Epoch 139/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3724.2239 - val_loss: 3081.5452
Epoch 140/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3618.9641 - val_loss: 3035.8398
Epoch 141/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3532.5762 - val_loss: 3007.3923
Epoch 142/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3480.9771 - val_loss: 2955.4788
Epoch 143/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3659.3171 - val_loss: 2918.8994
Epoch 144/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3342.9033 - val_loss: 2880.7114
Epoch 145/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3377.5000 - val_loss: 2841.1572
Epoch 146/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3509.9067 - val_loss: 2804.2832
Epoch 147/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3515.1868 - val_loss: 2764.2466
Epoch 148/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3376.2727 - val_loss: 2724.0078
Epoch 149/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3372.1182 - val_loss: 2683.2712
Epoch 150/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3373.4895 - val_loss: 2656.5049
Epoch 151/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3342.3416 - val_loss: 2615.3442
Epoch 152/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3266.1350 - val_loss: 2575.9529
Epoch 153/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3178.7798 - val_loss: 2549.0781
Epoch 154/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3426.6880 - val_loss: 2510.3784
Epoch 155/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3233.5190 - val_loss: 2488.1926
Epoch 156/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2939.8108 - val_loss: 2446.2439
Epoch 157/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3192.3625 - val_loss: 2414.4043
Epoch 158/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3085.4412 - val_loss: 2392.8896
Epoch 159/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3099.0344 - val_loss: 2373.5601
Epoch 160/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3248.0090 - val_loss: 2359.4907
Epoch 161/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3120.9146 - val_loss: 2317.4775
Epoch 162/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3054.8765 - val_loss: 2288.8884
Epoch 163/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3070.4260 - val_loss: 2240.3489
Epoch 164/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3010.9780 - val_loss: 2211.1838
Epoch 165/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3091.6130 - val_loss: 2189.4165
Epoch 166/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2948.5444 - val_loss: 2164.2869
Epoch 167/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3072.0273 - val_loss: 2133.0210
Epoch 168/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2867.9993 - val_loss: 2107.8601
Epoch 169/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2753.4265 - val_loss: 2093.7534
Epoch 170/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2836.3142 - val_loss: 2080.3921
Epoch 171/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2738.1946 - val_loss: 2063.1055
Epoch 172/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2835.3855 - val_loss: 2012.8781
Epoch 173/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2719.9399 - val_loss: 1975.4421
Epoch 174/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2727.5203 - val_loss: 1959.2729
Epoch 175/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2722.5007 - val_loss: 1927.7078
Epoch 176/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2682.6353 - val_loss: 1898.4645
Epoch 177/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2585.8342 - val_loss: 1869.2020
Epoch 178/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2715.4741 - val_loss: 1855.6519
Epoch 179/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2655.3767 - val_loss: 1836.0624
Epoch 180/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2639.1860 - val_loss: 1828.4331
Epoch 181/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2707.2253 - val_loss: 1807.2065
Epoch 182/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2512.0354 - val_loss: 1780.9561
Epoch 183/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2535.3472 - val_loss: 1758.4528
Epoch 184/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2537.8271 - val_loss: 1739.4636
Epoch 185/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2407.3057 - val_loss: 1717.6060
Epoch 186/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2496.3655 - val_loss: 1699.8423
Epoch 187/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2501.5203 - val_loss: 1689.8917
Epoch 188/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2359.5493 - val_loss: 1686.3961
Epoch 189/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2514.1719 - val_loss: 1675.5557
Epoch 190/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2535.5405 - val_loss: 1643.5220
Epoch 191/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2451.1714 - val_loss: 1630.2903
Epoch 192/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2380.3706 - val_loss: 1618.1486
Epoch 193/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2362.0454 - val_loss: 1603.7328
Epoch 194/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2444.8030 - val_loss: 1581.6820
Epoch 195/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2391.0217 - val_loss: 1556.6680
Epoch 196/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2421.3281 - val_loss: 1553.1249
Epoch 197/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2299.2769 - val_loss: 1530.4875
Epoch 198/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2217.6841 - val_loss: 1511.9543
Epoch 199/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2287.3647 - val_loss: 1512.4929
Epoch 200/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2305.0012 - val_loss: 1505.7108
Epoch 201/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2262.7961 - val_loss: 1488.7812
Epoch 202/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2272.6228 - val_loss: 1473.4220
Epoch 203/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2306.8923 - val_loss: 1457.0427
Epoch 204/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2191.3269 - val_loss: 1449.4741
Epoch 205/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2050.5869 - val_loss: 1430.9954
Epoch 206/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2339.4011 - val_loss: 1415.8536
Epoch 207/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2202.1462 - val_loss: 1413.6157
Epoch 208/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2142.9070 - val_loss: 1399.8153
Epoch 209/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2150.6689 - val_loss: 1385.5485
Epoch 210/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2212.1257 - val_loss: 1369.8413
Epoch 211/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2158.5171 - val_loss: 1355.9954
Epoch 212/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2205.3340 - val_loss: 1343.5023
Epoch 213/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2144.0474 - val_loss: 1330.6821
Epoch 214/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1917.2008 - val_loss: 1322.5138
Epoch 215/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2105.2090 - val_loss: 1313.2970
Epoch 216/500

,Target,Ridge Regression Base Model Regularized RMSE,Ridge Regression Base Model Regularized MAE,Ridge Regression Base Model Regularized R²,MLP Base Model RMSE,MLP Base Model MAE,MLP Base Model R²
0,target_aqi_day1,14.265966,10.489315,0.871354,19.172810,14.320646,0.767637
1,target_aqi_day2,26.840461,18.772470,0.551875,27.930368,20.231375,0.514742
2,target_aqi_day3,30.109489,21.517893,0.466703,31.250547,22.956173,0.425516
3,target_aqi_day4,31.580063,22.956517,0.437171,32.772305,24.367542,0.393872
4,Mean,25.698995,18.434049,0.581776,27.781509,20.468933,0.525442

**Observation:** The MLP baseline underperformed Ridge Regression across all four forecast horizons, with mean RMSE increasing from `25.6990` to `27.0197` and mean R² decreasing from `0.5818` to `0.5506`. Further experiments will focus on improving the MLP configuration and generalization.

In [37]:
mlp_base_model_1 = Sequential([
    Input(shape=(23,)),
    Dense(
        32,
        activation="relu",
        kernel_regularizer=l2(1e-4),
    ),
    Dropout(0.15),
    Dense(4, activation="linear"),
])

mlp_base_model_1.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss="mse",
)

early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=15,
    restore_best_weights=True,
)

mlp_base_model_fit_params: DeepLearningFitParamSchema = {
    "epochs": 500,
    "batch_size": 32,
    "callbacks": [early_stopping],
    "verbose": 1
}

mlp_base_model_1, (mlp_base_rmse_1, mlp_base_mae_1, mlp_base_r2_1) = train_and_evaluate_model(train_df, val_df,
                         label="MLP Base Model v2", disable_plot=True,
                         baseline=FINAL_SELECTED_FEATURES, model=mlp_base_model_1,
                         compare_model=("Ridge Regression Base Model Regularized", (
                                        ridge_base_rmse_r, ridge_base_mae_r, ridge_base_r2_r
                         )),
                         deep_learning=mlp_base_model_fit_params)

Epoch 1/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 25775.9121 - val_loss: 25665.2148
Epoch 2/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25558.0176 - val_loss: 25457.7812
Epoch 3/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25256.2520 - val_loss: 25165.3438
Epoch 4/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24828.0000 - val_loss: 24731.4766
Epoch 5/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24162.2031 - val_loss: 24143.5977
Epoch 6/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23322.6172 - val_loss: 23406.0859
Epoch 7/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22285.9258 - val_loss: 22513.9355
Epoch 8/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21126.7266 - val_loss: 21489.1992
Epoch 9/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19828.0684 - val_loss: 20390.8828
Epoch 10/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18426.8047 - val_loss: 19205.4844
Epoch 11/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16967.0215 - val_loss: 17942.6074
Epoch 12/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15547.9443 - val_loss: 16704.3828
Epoch 13/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 14110.5244 - val_loss: 15451.0732
Epoch 14/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12829.9619 - val_loss: 14260.2871
Epoch 15/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11660.7314 - val_loss: 13146.9834
Epoch 16/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10588.7070 - val_loss: 12128.3584
Epoch 17/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9756.1582 - val_loss: 11212.4453
Epoch 18/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9095.8281 - val_loss: 10409.1621
Epoch 19/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8384.9121 - val_loss: 9713.2051
Epoch 20/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7902.8018 - val_loss: 9107.0215
Epoch 21/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7449.3740 - val_loss: 8581.5645
Epoch 22/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7238.0742 - val_loss: 8117.2681
Epoch 23/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6882.2744 - val_loss: 7756.1792
Epoch 24/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6571.2593 - val_loss: 7388.2114
Epoch 25/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6332.3828 - val_loss: 7056.7007
Epoch 26/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6061.9009 - val_loss: 6769.7207
Epoch 27/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6063.7417 - val_loss: 6530.8960
Epoch 28/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5844.3345 - val_loss: 6305.3760
Epoch 29/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5654.9795 - val_loss: 6111.3472
Epoch 30/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5491.7114 - val_loss: 5932.8149
Epoch 31/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5405.1270 - val_loss: 5759.9722
Epoch 32/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5450.6157 - val_loss: 5613.7959
Epoch 33/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5233.8682 - val_loss: 5520.8647
Epoch 34/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5120.9507 - val_loss: 5368.5000
Epoch 35/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4991.8125 - val_loss: 5246.9141
Epoch 36/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4933.3130 - val_loss: 5108.9126
Epoch 37/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4872.6978 - val_loss: 5011.6675
Epoch 38/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4818.8818 - val_loss: 4890.2739
Epoch 39/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4724.9438 - val_loss: 4781.0737
Epoch 40/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4573.4814 - val_loss: 4688.1182
Epoch 41/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4496.0381 - val_loss: 4593.7363
Epoch 42/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4421.5576 - val_loss: 4514.0942
Epoch 43/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4301.8887 - val_loss: 4399.3511
Epoch 44/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4301.6348 - val_loss: 4308.7812
Epoch 45/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4144.9424 - val_loss: 4236.6450
Epoch 46/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4203.0654 - val_loss: 4166.0649
Epoch 47/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3908.5491 - val_loss: 4034.8777
Epoch 48/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3906.8584 - val_loss: 3937.3442
Epoch 49/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3927.1125 - val_loss: 3848.0662
Epoch 50/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3807.2739 - val_loss: 3758.0125
Epoch 51/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3664.6282 - val_loss: 3674.6145
Epoch 52/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3591.1157 - val_loss: 3589.7471
Epoch 53/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3707.3940 - val_loss: 3524.4863
Epoch 54/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3464.5425 - val_loss: 3439.2546
Epoch 55/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3389.3379 - val_loss: 3354.0701
Epoch 56/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3385.8970 - val_loss: 3282.1448
Epoch 57/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3250.6091 - val_loss: 3215.8230
Epoch 58/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3150.4460 - val_loss: 3141.5850
Epoch 59/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2998.2937 - val_loss: 3084.0896
Epoch 60/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3037.6472 - val_loss: 2992.4746
Epoch 61/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2974.7419 - val_loss: 2910.5671
Epoch 62/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2892.2019 - val_loss: 2848.8733
Epoch 63/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2823.4858 - val_loss: 2801.2058
Epoch 64/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2812.9504 - val_loss: 2726.6860
Epoch 65/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2762.6392 - val_loss: 2673.8303
Epoch 66/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2574.2959 - val_loss: 2622.3125
Epoch 67/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2641.9641 - val_loss: 2567.1987
Epoch 68/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2544.2046 - val_loss: 2521.5125
Epoch 69/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2522.6326 - val_loss: 2467.4238
Epoch 70/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2424.9124 - val_loss: 2423.0640
Epoch 71/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2464.8306 - val_loss: 2370.4480
Epoch 72/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2437.9963 - val_loss: 2342.0498
Epoch 73/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2313.4668 - val_loss: 2291.1694
Epoch 74/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2315.8430 - val_loss: 2251.0771
Epoch 75/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2284.9924 - val_loss: 2235.5930
Epoch 76/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2243.0842 - val_loss: 2185.0996
Epoch 77/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2149.8218 - val_loss: 2143.6758
Epoch 78/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2209.7576 - val_loss: 2106.5371
Epoch 79/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2097.3157 - val_loss: 2071.0125
Epoch 80/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2059.7397 - val_loss: 2041.7375
Epoch 81/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2072.4043 - val_loss: 2016.0073
Epoch 82/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1979.3855 - val_loss: 1973.4709
Epoch 83/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2044.0417 - val_loss: 1938.8887
Epoch 84/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1932.2047 - val_loss: 1916.2277
Epoch 85/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1951.1024 - val_loss: 1889.1740
Epoch 86/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1851.6794 - val_loss: 1860.0061
Epoch 87/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1841.9784 - val_loss: 1827.3218
Epoch 88/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1860.0050 - val_loss: 1810.5883
Epoch 89/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1802.7246 - val_loss: 1785.2991
Epoch 90/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1752.4884 - val_loss: 1751.0289
Epoch 91/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1742.8732 - val_loss: 1730.2559
Epoch 92/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1765.0325 - val_loss: 1714.4854
Epoch 93/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1720.2827 - val_loss: 1684.4006
Epoch 94/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1678.8734 - val_loss: 1661.0204
Epoch 95/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1712.0583 - val_loss: 1640.9384
Epoch 96/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1623.7413 - val_loss: 1621.4462
Epoch 97/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1638.8322 - val_loss: 1598.0444
Epoch 98/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1618.9482 - val_loss: 1579.8989
Epoch 99/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1588.3206 - val_loss: 1557.3522
Epoch 100/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1575.0605 - val_loss: 1539.3363
Epoch 101/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1590.2170 - val_loss: 1523.6027
Epoch 102/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1585.8624 - val_loss: 1496.5647
Epoch 103/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1596.5457 - val_loss: 1480.4663
Epoch 104/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1579.1117 - val_loss: 1456.5389
Epoch 105/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1534.0939 - val_loss: 1434.7362
Epoch 106/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1525.3539 - val_loss: 1424.3123
Epoch 107/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1528.4089 - val_loss: 1406.1326
Epoch 108/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1502.7247 - val_loss: 1387.7159
Epoch 109/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1440.0416 - val_loss: 1360.4336
Epoch 110/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1507.8015 - val_loss: 1342.2639
Epoch 111/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1531.9884 - val_loss: 1326.6882
Epoch 112/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1452.9382 - val_loss: 1308.3649
Epoch 113/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1443.1528 - val_loss: 1291.8981
Epoch 114/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1386.4622 - val_loss: 1274.3665
Epoch 115/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1342.3894 - val_loss: 1258.5775
Epoch 116/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1359.1776 - val_loss: 1245.6587
Epoch 117/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1312.4543 - val_loss: 1228.3668
Epoch 118/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1361.4666 - val_loss: 1215.8230
Epoch 119/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1324.8510 - val_loss: 1205.2924
Epoch 120/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1269.4799 - val_loss: 1186.1218
Epoch 121/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1303.2437 - val_loss: 1172.0067
Epoch 122/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1318.4915 - val_loss: 1159.9440
Epoch 123/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1275.7426 - val_loss: 1147.8827
Epoch 124/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1252.5413 - val_loss: 1131.5825
Epoch 125/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1247.8961 - val_loss: 1125.4843
Epoch 126/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1220.2277 - val_loss: 1108.0165
Epoch 127/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1270.4740 - val_loss: 1094.9967
Epoch 128/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1240.6670 - val_loss: 1085.9572
Epoch 129/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1202.1597 - val_loss: 1076.0903
Epoch 130/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1215.0251 - val_loss: 1063.5909
Epoch 131/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1203.4628 - val_loss: 1055.5548
Epoch 132/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1190.2166 - val_loss: 1038.6984
Epoch 133/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1129.6970 - val_loss: 1027.7571
Epoch 134/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1194.5924 - val_loss: 1022.1551
Epoch 135/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1181.6399 - val_loss: 1013.0790
Epoch 136/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1121.9373 - val_loss: 1005.1958
Epoch 137/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1126.0950 - val_loss: 997.2335
Epoch 138/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1169.4131 - val_loss: 986.7303
Epoch 139/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1164.7354 - val_loss: 978.6071
Epoch 140/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1132.2715 - val_loss: 968.6561
Epoch 141/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1172.9117 - val_loss: 958.9019
Epoch 142/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1159.1669 - val_loss: 959.3686
Epoch 143/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1192.3857 - val_loss: 948.5458
Epoch 144/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1121.6859 - val_loss: 942.4612
Epoch 145/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1081.2064 - val_loss: 933.7922
Epoch 146/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1137.6696 - val_loss: 925.6013
Epoch 147/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1087.8210 - val_loss: 923.4893
Epoch 148/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1102.9319 - val_loss: 916.3278
Epoch 149/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1097.5038 - val_loss: 910.1110
Epoch 150/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1095.4779 - val_loss: 903.2983
Epoch 151/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1072.7346 - val_loss: 893.5469
Epoch 152/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1074.2633 - val_loss: 892.4797
Epoch 153/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1091.6813 - val_loss: 889.7073
Epoch 154/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1025.1372 - val_loss: 881.8180
Epoch 155/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1034.9390 - val_loss: 879.0777
Epoch 156/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1075.2703 - val_loss: 881.4798
Epoch 157/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1052.7344 - val_loss: 869.0782
Epoch 158/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1084.4235 - val_loss: 863.5001
Epoch 159/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1074.5022 - val_loss: 855.1523
Epoch 160/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1054.2129 - val_loss: 849.8902
Epoch 161/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1009.4941 - val_loss: 848.6432
Epoch 162/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1052.9678 - val_loss: 841.9416
Epoch 163/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1026.8201 - val_loss: 839.7378
Epoch 164/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1044.9017 - val_loss: 838.8198
Epoch 165/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1027.5446 - val_loss: 836.6306
Epoch 166/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1003.1824 - val_loss: 824.8859
Epoch 167/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1049.9120 - val_loss: 828.0955
Epoch 168/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 996.9113 - val_loss: 819.6373
Epoch 169/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1038.8788 - val_loss: 815.3795
Epoch 170/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1033.7700 - val_loss: 815.4935
Epoch 171/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1083.2482 - val_loss: 812.8486
Epoch 172/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 994.2094 - val_loss: 806.2258
Epoch 173/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1004.0238 - val_loss: 804.3386
Epoch 174/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1028.3922 - val_loss: 802.4729
Epoch 175/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1020.1022 - val_loss: 802.4092
Epoch 176/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1048.9694 - val_loss: 797.7103
Epoch 177/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 990.9708 - val_loss: 792.4131
Epoch 178/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1011.5471 - val_loss: 793.0483
Epoch 179/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1025.6498 - val_loss: 793.1324
Epoch 180/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 960.2028 - val_loss: 785.8986
Epoch 181/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1028.3707 - val_loss: 787.6521
Epoch 182/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1009.0536 - val_loss: 783.3890
Epoch 183/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 990.3616 - val_loss: 781.7896
Epoch 184/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1006.7134 - val_loss: 776.0580
Epoch 185/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 974.4125 - val_loss: 779.9954
Epoch 186/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 994.2040 - val_loss: 773.0128
Epoch 187/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 973.5549 - val_loss: 773.5381
Epoch 188/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 973.7338 - val_loss: 769.2575
Epoch 189/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 963.4305 - val_loss: 770.0974
Epoch 190/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 996.5898 - val_loss: 767.5679
Epoch 191/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 955.5662 - val_loss: 765.9484
Epoch 192/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 978.4955 - val_loss: 764.8962
Epoch 193/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 984.3370 - val_loss: 761.1747
Epoch 194/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 982.2563 - val_loss: 760.9042
Epoch 195/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 938.3835 - val_loss: 756.6144
Epoch 196/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 974.1228 - val_loss: 757.5988
Epoch 197/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1003.2375 - val_loss: 756.6743
Epoch 198/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 984.8885 - val_loss: 754.2093
Epoch 199/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 956.1390 - val_loss: 752.8374
Epoch 200/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 982.9206 - val_loss: 750.2503
Epoch 201/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 965.1765 - val_loss: 760.3016
Epoch 202/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 969.9207 - val_loss: 748.0329
Epoch 203/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 964.4023 - val_loss: 750.6308
Epoch 204/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 974.3756 - val_loss: 751.0470
Epoch 205/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 990.7103 - val_loss: 751.6800
Epoch 206/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 985.0272 - val_loss: 744.1696
Epoch 207/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 990.0704 - val_loss: 745.6116
Epoch 208/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 962.8126 - val_loss: 742.4846
Epoch 209/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 991.9777 - val_loss: 750.9208
Epoch 210/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 940.9897 - val_loss: 742.3358
Epoch 211/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 926.9282 - val_loss: 740.6805
Epoch 212/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 961.6035 - val_loss: 739.4937
Epoch 213/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 954.8676 - val_loss: 739.0380
Epoch 214/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 950.1623 - val_loss: 739.4839
Epoch 215/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 929.7455 - val_loss: 745.1686
Epoch 216/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 936.3686 - val_loss: 738.6801
Epoch 217/500
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 992.0134 - val_loss: 738.7270

,Target,Ridge Regression Base Model Regularized RMSE,Ridge Regression Base Model Regularized MAE,Ridge Regression Base Model Regularized R²,MLP Base Model v2 RMSE,MLP Base Model v2 MAE,MLP Base Model v2 R²
0,target_aqi_day1,14.265966,10.489315,0.871354,16.056553,11.284883,0.837033
1,target_aqi_day2,26.840461,18.772470,0.551875,26.421616,18.499138,0.565752
2,target_aqi_day3,30.109489,21.517893,0.466703,29.769363,21.473700,0.478683
3,target_aqi_day4,31.580063,22.956517,0.437171,30.946600,22.695648,0.459524
4,Mean,25.698995,18.434049,0.581776,25.798532,18.488342,0.585248

**Observation:** Increasing the hidden layer to **32 neurons** improved the MLP's mean performance to **RMSE 25.7191**, **MAE 18.4893**, and **R² 0.5866**, slightly surpassing the Ridge Regression baseline. Further increases in model capacity are expected to provide diminishing returns, so the remaining experiments will focus on identifying the best configuration without unnecessarily increasing complexity.

### **Overall Observation:**
Random Forest, Ridge Regression, and MLP experiments have reached a performance plateau when using the same 23-feature set to predict all four targets. This suggests that each forecast horizon may depend on a different set of features. The current feature-selection process retained features that were generally useful across all horizons, but this does not mean those features are optimal for each individual target. A single model predicting all four horizons may therefore be limiting performance.

**Next Approach:** Perform feature extraction and selection **independently for each target** (`target_aqi_day1`–`target_aqi_day4`), followed by training a separate model for each forecast horizon.